package com.demo.common.model;

import com.demo.model.Authority;
import com.demo.model.Role;
import com.demo.model.User;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;


/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sec_users", User.class);
		arp.addMapping("sec_roles", Role.class);
		arp.addMapping("sec_auths", Authority.class);
	}
}

